### PR TITLE
Add configurable delays to STOP.js listeners.

### PR DESCRIPTION
**Pull request by CuddleBunny**

### CODE REVIEW

**Comment by aveao** [comment]
ouch, I forgot. Will check in 6-7 hours.

**Comment by CuddleBunny** [comment]
No rush, take your time.

**Comment by aveao** [comment]
Fails silently, totally breaks the STOP.js, weird.

**Comment by CuddleBunny** [comment]
Cool, I won't bother spinning up a test environment then. Will wait for the re-write.

**Pull request closed without merging**
